### ISSUE TITLE
Add about speeding up makepkg

### ISSUE THREAD

**Issue by aaravrav** [sn99/Optimizing-linux#14]
This mainly applies to rolling release distros like arch and gentoo which use makepkg to compile their packages. Since you are on nobara I am not sure if this warrants a section in the guide, do as you wish.

See: https://www.reddit.com/r/archlinux/comments/1d6zij6/small_tip_to_speed_up_aur_installs/

Do see the full thread.

**Comment by sn99** [comment]
Feel free to open a PR @aarav2you , we can just mention it alongside: `on arch you add these additional flags ...`
