### ISSUE TITLE
xanmod, ananicy, arch

### ISSUE THREAD

**Issue by dim-geo** [sn99/Optimizing-linux#3]
Hello,

please check [xanmod](https://xanmod.org/) kernel source which is configured for desktops.
[Ananicy](https://github.com/Nefelim4ag/Ananicy) which is an application to prioritize desktop applications and the excellent [Arch wiki.](https://wiki.archlinux.org/index.php/Improving_performance)

**Comment by sn99** [comment]
Xanmod if I remember was  `amd` optimized but I do like some of it's patches, I am thinking of making an easy to search basic site to let people link to their patches and such.

I will link the other two.
